name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.1.0

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  image_picker: ^1.2.1
  flutter_local_notifications: ^17.2.2
  shared_preferences: ^2.5.4
  http: ^1.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  flutter_launcher_icons: ^0.13.1

  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/icon/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png" 
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icon/logo1.png"

  android_12:
    image: "assets/icon/logo1.png"
    color: "#FFFFFF"